### ISSUE TITLE
CreatePost Componen

### ISSUE THREAD

**Issue by Mainm0e** [Mainm0e/social-network#25]
UX/ UI
CreatePost componen need to have
*Input*
-title
-content
-import file
- privecy select
- submit

**Comment by Mainm0e** [comment]
@salam-github  please can you draw some this componen for me befor monday.
"if you have time you can create it too."

**Comment by Mainm0e** [comment]
<img width="1158" alt="Screenshot 2023-06-16 at 18 02 36" src="https://github.com/Mainm0e/social-network/assets/97899359/e051b80e-4380-4ad3-a730-a5e5fe631bc8">
you can see this file in my branch frontend/ui/create_post.dio

**Comment by Mainm0e** [comment]
you need to 
<img width="692" alt="Screenshot 2023-06-16 at 18 05 21" src="https://github.com/Mainm0e/social-network/assets/97899359/c5d2cfcc-2792-4919-80f7-0de6093d869d">
to open file

**Comment by maryamkheirkhah** [comment]
@salam-github 
creating post in personal profiles and groups are different.
in personal post you have those option that we talk about : private, public, semi-private(selecting followers)
but in create group post we shouldn't have those options, it will be shown to all group members with no condition.

**Comment by Mainm0e** [comment]
semi-private system need to add

**Comment by maryamkheirkhah** [comment]
can we close it ?
